### PR TITLE
fix: Fix for #190, broken nodejs sdk test.

### PR DESCRIPTION
**Pull request by domderen**
Fix for #190

### CODE REVIEW

**Comment by alexec** [comment]
you'll want to re-enable the test too

**Comment by domderen** [comment]
Give it a moment, it's still failing for some reason.

**Comment by domderen** [comment]
I'm trying to figure out why.

**Comment by domderen** [comment]
I think this is the problem with those tests:

```
time="2021-08-04T08:11:01Z" level=info msg="updating step" logger=controllers.Step patch="{\"message\":\"Container image \\\"node:16\\\" is not present with pull policy of Never\",\"reason\":\"ErrImageNeverPull\"}" step="{\"Namespace\":\"argo-dataflow-system\",\"Name\":\"106-git-nodejs-main\"}"

...

time="2021-08-04T08:13:32Z" level=info msg="updating step" logger=controllers.Step patch="{\"message\":\"Container image \\\"python:3.9\\\" is not present with pull policy of Never\",\"reason\":\"ErrImageNeverPull\"}" step="{\"Namespace\":\"argo-dataflow-system\",\"Name\":\"106-git-python-main\"}"
```

I'm re-trying with different PullImagePolicy, though I think this is a hack that can't be merged into the repo. Maybe those images should be pre-pulled in docker to make them available during build? Or maybe the python example should use `python:3.9-alpine` docker image, same as the runtime example?

**Review by alexec — APPROVED** [review]

**Pull request merged**
