### PR TITLE
feat: NodeJS SDK for handling the container contract

### PR DESCRIPTION
**Pull request by domderen**
This PR adds a NodeJS SDK capable of handling the container contract. I wasn't sure if the new authentication requirement in the image contract was finalized or not yet, so I didn't add it yet.

### CODE REVIEW

**Comment by alexec** [comment]
Excellent. Can you add "NodeJS SDK" to FEATURES.md?

**Comment by alexec** [comment]
Note - I don't test your PRs.

**Comment by domderen** [comment]
Haha I noticed that :P I do test them before pushing them out, but I'm still learning the repo, and I'm doing it on my own free time, so hopefully it will run smoothly :) I'll add the it to `FEATURES.md` and will add some style fixes to this one in another PR.

**Comment by alexec** [comment]
FEATURES.md if for a user to ask "I want to use feature X, but is it ready?"

**Pull request merged**
